### PR TITLE
Fix vehicle and player submenu

### PR DESCRIPTION
**Pull request by Saturn745**
Makes the "Player Related Options" and "Vehicle Related Options" actually switch to the submenu when clicked.

### CODE REVIEW

**Comment by manups4e** [comment]
🤔 apparently this PR has conflicts

**Comment by Saturn745** [comment]
> 🤔 apparently this PR has conflicts

😞 Probably because I accidentally committed the keymapping to this branch then undid it. I'll fix it when I get home

**Comment by manups4e** [comment]
no problem :D i'll wait take your time

**Comment by Saturn745** [comment]
Managed to do it on my phone 🙂

**Pull request merged**
